import {OsaekomiWaza, ShimeWaza, TeWaza, AshiWaza, KansetsuWaza, KoshiWaza, SutemiWaza} from './types';

export const osaekomiWaza: { [name: string]: OsaekomiWaza } = {
    'KesaGatame': {
        image: 'https://www.judopourtous.com/Images/NeHonGesaGatame.gif',
        prise: undefined,
        positionTori: 'dessus',
        variante: ['KuzureKesaGatame']
    },
    'KuzureKesaGatame': {
        image: 'https://www.judopourtous.com/Images/NeHonGesaGatame.gif',
        prise: undefined,
        positionTori: 'dessus',
    },
    'TateShihoGatame': {
        image: 'https://www.judopourtous.com/Images/NeTateShihoGatame.gif',
        prise: undefined,
        positionTori: 'dessus',
    },
    'UshiroKesaGatame': {
        image: 'https://www.judopourtous.com/Images/NeUshiroGesaGatame.gif',
        prise: undefined,
        positionTori: 'derriere',
    },
    'KamiShihoGatame': {
        image: 'https://www.judopourtous.com/Images/NeKamiShihoGatame.gif',
        prise: undefined,
        positionTori: 'dessus',
    },
    'KuzureKamiShihoGatame': {
        image: 'https://www.judopourtous.com/Images/NeKamiShihoGatame.gif',
        prise: undefined,
        positionTori: 'dessus',
    },
    'YokoShihoGatame': {
        image: 'https://www.judopourtous.com/Images/NeYokoShihoGatame.gif',
        prise: undefined,
        positionTori: 'cote',
        variante: ['KuzureYokoShihoGatame']
    },
    'KuzureYokoShihoGatame': {
        image: 'https://www.judopourtous.com/Images/NeYokoShihoGatame.gif',
        prise: undefined,
        positionTori: 'cote',
    },
    'UkiGatame': {
        image: 'https://www.judopourtous.com/Images/TechniquesOublieesUkiGatame.jpg',
        prise: undefined,
        positionTori: 'dessus',
    },
    'KataGatame': {
        image: 'https://www.judopourtous.com/Images/NeKataGatame.gif',
        prise: undefined,
        positionTori: 'cote',
    },
    'KuzureKataGatame': {
        image: 'https://www.judopourtous.com/Images/NeKataGatame.gif',
        prise: undefined,
        positionTori: 'cote',
    }
};

export const shimeWaza: {[name: string]: ShimeWaza} = {
  'HadakaJime': {
    image: 'https://www.judopourtous.com/Images/NeHadakaJime.gif',
    prise: 'sansGi',
    variante: ['KataHaJime'],
    positionUke: 'dos',
    positionTori: 'dessus',
    type: 'sanguin',
    membresUtilises: ['bras'],
    directionPression: 'circulaire',
  },
  'JujiJime': {
    image: 'https://www.judopourtous.com/Images/NeGyakuJujiJime.gif',
    prise: 'croisee',
    positionUke: 'dos',
    positionTori: 'dessus',
    type: 'sanguin',
    membresUtilises: ['bras','revers'],
    directionPression: 'circulaire',
  },
  'OkuriEriJime': {
    image: 'https://www.judopourtous.com/Images/NeOkuriEriJime.gif',
    prise: 'classique',
    positionUke: 'debout',
    positionTori: 'derriere',
    type: 'sanguin',
    membresUtilises: ['bras','revers'],
    directionPression: 'laterale',
  },
  'KataJujiJime': {
    image: 'https://www.judopourtous.com/Images/NeTsukkomiJime.gif',
    prise: 'croisee',
    positionUke: 'dos',
    positionTori: 'dessus',
    type: 'sanguin',
    membresUtilises: ['bras','revers'],
    directionPression: 'circulaire',
  },
  'NamiJujiJime': {
    image: 'https://www.judopourtous.com/Images/NeTsukkomiJime.gif',
    prise: 'croisee',
    positionUke: 'dos',
    positionTori: 'dessus',
    type: 'sanguin',
    membresUtilises: ['bras','revers'],
    directionPression: 'circulaire',
  },
  'GyakuJujiJime': {
    image: 'https://www.judopourtous.com/Images/NeTsukkomiJime.gif',
    prise: 'croisee',
    positionUke: 'dos',
    positionTori: 'dessus',
    type: 'sanguin',
    membresUtilises: ['bras','revers'],
    directionPression: 'circulaire',
  },
  'KataHaJime': {
    image: 'https://www.judopourtous.com/Images/NeKataHaJime.gif',
    prise: 'croisee',
    positionUke: 'dos',
    positionTori: 'dessus',
    type: 'sanguin',
    membresUtilises: ['bras','revers'],
    directionPression: 'circulaire',
  },
  'SodeGurumaJime': {
    image: 'https://www.judopourtous.com/Images/NeSodeGurumaJime.gif',
    prise: 'doubleRevers',
    positionUke: 'dos',
    positionTori: 'dessus',
    type: 'sanguin',
    membresUtilises: ['bras','revers'],
    directionPression: 'circulaire',
  },
  'KataEriJime': {
    image: 'https://www.judopourtous.com/Images/NeKataTeJime.jpg',
    prise: 'classique',
    positionUke: 'dos',
    positionTori: 'dessus',
    type: 'sanguin',
    membresUtilises: ['bras'],
    directionPression: 'circulaire',
  },
  'OkuriEriJimeAssis': {
    image: 'https://www.judopourtous.com/Images/NeOkuriEriJime.gif',
    prise: 'classique',
    positionUke: 'assis',
    positionTori: 'derriere',
    type: 'sanguin',
    membresUtilises: ['bras','revers'],
    directionPression: 'laterale',
  },
  'TsukkomiJime': {
    image: 'https://www.judopourtous.com/Images/NeTsukkomiJime.gif',
    prise: 'classique',
    positionUke: 'ventre',
    positionTori: 'dessus',
    type: 'respiratoire',
    membresUtilises: ['bras'],
    directionPression: 'laterale',
  },
};

export const kansetsuWaza: {[name: string]: KansetsuWaza} = {
  'JujiGatame': {
    image: 'https://www.judopourtous.com/Images/NeJujiGatame.gif',
    prise: 'classique',
    positionUke: 'dos',
    positionTori: 'dessus',
    articulation: 'coude',
    typeLevier: 'hyperextension',
  },
  'UdeGarami': {
    image: 'https://www.judopourtous.com/Images/NeUdeGarami.gif',
    prise: 'classique',
    positionUke: 'dos',
    positionTori: 'dessus',
    articulation: 'coude',
    typeLevier: 'torsion',
  },
  'UdeHishigiUdeGatame': {
    image: 'https://www.judopourtous.com/Images/NeUdeHishigiUdeGatame.gif',
    prise: 'classique',
    positionUke: 'dos',
    positionTori: 'dessus',
    articulation: 'coude',
    typeLevier: 'hyperextension',
  },
  'UdeHishigiJujiGatame': {
    image: 'https://www.judopourtous.com/Images/NeUdeHishigiJujiGatame.gif',
    prise: 'classique',
    positionUke: 'dos',
    positionTori: 'dessus',
    articulation: 'coude',
    typeLevier: 'hyperextension',
  },
  'UdeHishigiHizaGatame': {
    image: 'https://www.judopourtous.com/Images/NeUdeHishigiHizaGatame.gif',
    prise: 'classique',
    positionUke: 'cote',
    positionTori: 'cote',
    articulation: 'coude',
    typeLevier: 'hyperextension',
  },
  'UdeHishigiWakiGatame': {
    image: 'https://www.judopourtous.com/Images/NeUdeHishigiWakiGatame.gif',
    prise: 'classique',
    positionUke: 'ventre',
    positionTori: 'dessus',
    articulation: 'coude',
    typeLevier: 'hyperextension',
  },
  'UdeHishigiHaraGatame': {
    image: 'https://www.judopourtous.com/Images/NeUdeHishigiHaraGatame.gif',
    prise: 'classique',
    positionUke: 'ventre',
    positionTori: 'dessus',
    articulation: 'coude',
    typeLevier: 'hyperextension',
  },
  'UdeHishigiAshiGatame': {
    image: 'https://www.judopourtous.com/Images/NeUdeHishigiAshiGatame.gif',
    prise: 'classique',
    positionUke: 'dos',
    positionTori: 'cote',
    articulation: 'coude',
    typeLevier: 'hyperextension',
  },
  // Variante / forme traditionnelle
  'AshiGarami': {
    image: 'https://www.judopourtous.com/Images/NeAshiGarami.gif',
    prise: undefined,
    positionUke: 'cote',
    positionTori: 'cote',
    articulation: 'coude',
    typeLevier: 'torsion',
  },
};

export const ashiWaza: {[name: string]: AshiWaza} = {
  'DeAshiHarai': {
    image: 'https://www.judopourtous.com/Images/NeDeAshiHarai.gif',
    prise: 'classique',
    variante: [],
    action: 'balayage',
    directionAR: undefined,
    directionLaterale: undefined,
    deplacementUke: 'lateral',
  },
  'OkuriAshiHarai': {
    image: 'https://www.judopourtous.com/Images/NeOkuriAshiHarai.gif',
    prise: 'classique',
    variante: [],
    action: 'balayage',
    directionAR: undefined,
    directionLaterale: undefined,
    deplacementUke: 'lateral',
  },
  'SasaeTsuriKomiAshi': {
    image: 'https://www.judopourtous.com/Images/NeSasaeTsuriKomiAshi.gif',
    prise: 'classique',
    variante: [],
    action: 'blocage',
    directionAR: 'avant',
    directionLaterale: undefined,
    deplacementUke: 'statique',
  },
  'HizaGuruma': {
    image: 'https://www.judopourtous.com/Images/NeHizaGuruma.gif',
    prise: 'classique',
    variante: [],
    action: 'blocage',
    directionAR: 'avant',
    directionLaterale: undefined,
    deplacementUke: 'statique',
  },
  'KoSotoGari': {
    image: 'https://www.judopourtous.com/Images/NeKoSotoGari.gif',
    prise: 'classique',
    variante: [],
    action: 'fauchage',
    directionAR: undefined,
    directionLaterale: 'droite',
    deplacementUke: 'statique',
  },
  'KoSotoGake': {
    image: 'https://www.judopourtous.com/Images/NeKoSotoGake.gif',
    prise: 'classique',
    variante: [],
    action: 'blocage',
    directionAR: undefined,
    directionLaterale: 'droite',
    deplacementUke: 'statique',
  },
  'KoUchiGari': {
    image: 'https://www.judopourtous.com/Images/NeKoUchiGari.gif',
    prise: 'classique',
    variante: [],
    action: 'fauchage',
    directionAR: undefined,
    directionLaterale: 'gauche',
    deplacementUke: 'statique',
  },
  'OUchiGari': {
    image: 'https://www.judopourtous.com/Images/NeOUchiGari.gif',
    prise: 'classique',
    variante: [],
    action: 'fauchage',
    directionAR: 'arriere',
    directionLaterale: undefined,
    deplacementUke: 'avance',
  },
  'AshiUchiMata': {
    image: 'https://www.judopourtous.com/Images/NeAshiUchiMata.gif',
    prise: 'classique',
    variante: ['KoUchiMata','OUchiMata','TakaUchiMata'],
    action: 'fauchage',
    directionAR: 'avant',
    directionLaterale: undefined,
    deplacementUke: 'avance',
  },
  'OSotoGari': {
    image: 'https://www.judopourtous.com/Images/NeOSotoGari.gif',
    prise: 'classique',
    variante: [],
    action: 'fauchage',
    directionAR: 'arriere',
    directionLaterale: undefined,
    deplacementUke: 'recule',
  },
  'OSotoGuruma': {
    image: 'https://www.judopourtous.com/Images/NeOSotoGuruma.gif',
    prise: 'classique',
    variante: [],
    action: 'blocage',
    directionAR: undefined,
    directionLaterale: undefined,
    deplacementUke: 'statique',
  },
  'HaraiTsurikomiAshi': {
    image: 'https://www.judopourtous.com/Images/NeHaraiTsurikomiAshi.gif',
    prise: 'classique',
    variante: [],
    action: 'balayage',
    directionAR: 'arriere',
    directionLaterale: undefined,
    deplacementUke: 'avance',
  },
  'AshiGuruma': {
    image: 'https://www.judopourtous.com/Images/NeAshiGuruma.gif',
    prise: 'classique',
    variante: [],
    action: 'blocage',
    directionAR: undefined,
    directionLaterale: undefined,
    deplacementUke: 'statique',
  },
  'OGuruma': {
    image: 'https://www.judopourtous.com/Images/NeOGuruma.gif',
    prise: 'classique',
    variante: [],
    action: 'blocage',
    directionAR: undefined,
    directionLaterale: undefined,
    deplacementUke: 'statique',
  },
  // Variantes / contres
  'TsubameGaeshi': {
    image: 'https://www.judopourtous.com/Images/NeTsubameGaeshi.gif',
    prise: undefined,
    action: 'balayage',
    directionAR: undefined,
    directionLaterale: undefined,
    deplacementUke: 'recule',
  },
  'OSotoGaeshi': {
    image: 'https://www.judopourtous.com/Images/NeOSotoGaeshi.gif',
    prise: undefined,
    action: 'fauchage',
    directionAR: undefined,
    directionLaterale: undefined,
    deplacementUke: 'recule',
  },
  'OUchiGaeshi': {
    image: 'https://www.judopourtous.com/Images/NeOUchiGaeshi.gif',
    prise: undefined,
    action: 'fauchage',
    directionAR: undefined,
    directionLaterale: undefined,
    deplacementUke: 'recule',
  },
  'KoUchiGaeshi1': {
    image: 'https://www.judopourtous.com/Images/NeKoUchiGaeshi.gif',
    prise: undefined,
    action: 'fauchage',
    directionAR: undefined,
    directionLaterale: undefined,
    deplacementUke: 'recule',
  },
  'KoUchiGaeshi2': {
    image: 'https://www.judopourtous.com/Images/NeKoUchiGaeshi.gif',
    prise: undefined,
    action: 'fauchage',
    directionAR: undefined,
    directionLaterale: undefined,
    deplacementUke: 'recule',
  },
  'UchiMataGaeshi': {
    image: 'https://www.judopourtous.com/Images/NeUchiMataGaeshi.gif',
    prise: undefined,
    action: 'balayage',
    directionAR: undefined,
    directionLaterale: undefined,
    deplacementUke: 'recule',
  },
};

export const teWaza: {[name: string]: TeWaza} = {
  'IpponSeoiNage': {
    image: 'https://www.judopourtous.com/Images/NeIpponSeoiNage.gif',
    prise: 'classique',
    variante: ['KatateSeoiNage'],
    brasDominant: 'droite',
    tractionPrincipale: 'avant',
    directionAR: 'avant',
    directionLaterale: undefined,
    deplacementUke: 'avance',
  },
  'MoroteSeoiNage': {
    image: 'https://www.judopourtous.com/Images/NeMoroteSeoiNage.gif',
    prise: 'classique',
    variante: [],
    brasDominant: 'droite',
    tractionPrincipale: 'avant',
    directionAR: 'avant',
    directionLaterale: undefined,
    deplacementUke: 'avance',
  },
  'EriSeoiNage': {
    image: 'https://www.judopourtous.com/Images/NeEriSeoiNage.gif',
    prise: 'croisee',
    variante: ['KataEriSeoi'],
    brasDominant: 'droite',
    tractionPrincipale: 'circulaire',
    directionAR: 'avant',
    directionLaterale: undefined,
    deplacementUke: 'avance',
  },
  'TaiOtoshi': {
    image: 'https://www.judopourtous.com/Images/NeTaiOtoshi.gif',
    prise: 'classique',
    variante: [],
    brasDominant: 'droite',
    tractionPrincipale: 'avant',
    directionAR: 'avant',
    directionLaterale: undefined,
    deplacementUke: 'statique',
  },
  'SumiOtoshi': {
    image: 'https://www.judopourtous.com/Images/NeSumiOtoshi.gif',
    prise: 'classique',
    variante: [],
    brasDominant: 'droite',
    tractionPrincipale: 'circulaire',
    directionAR: undefined,
    directionLaterale: 'gauche',
    deplacementUke: 'statique',
  },
  'KataGuruma': {
    image: 'https://www.judopourtous.com/Images/NeKataGuruma.gif',
    prise: 'classique',
    variante: [],
    brasDominant: 'droite',
    tractionPrincipale: 'haut',
    directionAR: 'avant',
    directionLaterale: undefined,
    deplacementUke: 'statique',
  },
  'UkiOtoshi': {
    image: 'https://www.judopourtous.com/Images/NeUkiOtoshi.gif',
    prise: 'classique',
    variante: [],
    brasDominant: 'droite',
    tractionPrincipale: 'circulaire',
    directionAR: 'avant',
    directionLaterale: undefined,
    deplacementUke: 'statique',
  },
  'TeGuruma': {
    image: 'https://www.judopourtous.com/Images/NeTeGuruma.gif',
    prise: 'classique',
    variante: ['SukuiNage'],
    brasDominant: 'droite',
    tractionPrincipale: 'haut',
    directionAR: 'avant',
    directionLaterale: undefined,
    deplacementUke: 'statique',
  },
  // Shimmeisho no waza potentiellement classés ici
  'MoroteGari': {
    image: 'https://www.judopourtous.com/Images/NeMoroteGari.gif',
    prise: undefined,
    variante: [],
    brasDominant: 'droite',
    tractionPrincipale: 'haut',
    directionAR: undefined,
    directionLaterale: undefined,
    deplacementUke: 'avance',
  },
  'KuchikiDaoshi': {
    image: 'https://www.judopourtous.com/Images/NeKuchikiDaoshi.gif',
    prise: undefined,
    variante: [],
    brasDominant: 'droite',
    tractionPrincipale: 'circulaire',
    directionAR: undefined,
    directionLaterale: undefined,
    deplacementUke: 'recule',
  },
  'KibisuGaeshi': {
    image: 'https://www.judopourtous.com/Images/NeKibisuGaeshi.gif',
    prise: undefined,
    variante: [],
    brasDominant: 'droite',
    tractionPrincipale: 'avant',
    directionAR: undefined,
    directionLaterale: undefined,
    deplacementUke: 'lateral',
  },
};

export const koshiWaza: {[name: string]: KoshiWaza} = {
  'OGoshi': {
    image: 'https://www.judopourtous.com/Images/NeOGoshi.gif',
    prise: 'classique',
    variante: [],
    contactHanche: 'frontal',
    directionAR: 'avant',
    directionLaterale: undefined,
    deplacementUke: 'avance',
  },
  'KoshiGuruma': {
    image: 'https://www.judopourtous.com/Images/NeKoshiGuruma.gif',
    prise: 'classique',
    variante: [],
    contactHanche: 'frontal',
    directionAR: 'avant',
    directionLaterale: undefined,
    deplacementUke: 'statique',
  },
  'TsuriGoshi': {
    image: 'https://www.judopourtous.com/Images/NeTsuriGoshi.gif',
    prise: 'classique',
    variante: ['OTsuriGoshi','KoTsuriGoshi'],
    contactHanche: 'frontal',
    directionAR: 'avant',
    directionLaterale: undefined,
    deplacementUke: 'avance',
  },
  'SodeTsuriKomiGoshi': {
    image: 'https://www.judopourtous.com/Images/NeSodeTsuriKomiGoshi.gif',
    prise: 'croisee',
    variante: [],
    contactHanche: 'frontal',
    directionAR: 'avant',
    directionLaterale: undefined,
    deplacementUke: 'statique',
  },
  'UkiGoshi': {
    image: 'https://www.judopourtous.com/Images/NeUkiGoshi.gif',
    prise: 'classique',
    variante: [],
    contactHanche: 'frontal',
    directionAR: 'avant',
    directionLaterale: undefined,
    deplacementUke: 'statique',
  },
  'UtsuriGoshi': {
    image: 'https://www.judopourtous.com/Images/NeUtsuriGoshi.gif',
    prise: 'classique',
    variante: [],
    contactHanche: 'frontal',
    directionAR: undefined,
    directionLaterale: undefined,
    deplacementUke: 'lateral',
  },
  'HaraiGoshi': {
    image: 'https://www.judopourtous.com/Images/NeHaraiGoshi.gif',
    prise: 'classique',
    variante: [],
    contactHanche: 'frontal',
    directionAR: 'avant',
    directionLaterale: 'droite',
    deplacementUke: 'avance',
  },
  'HaneGoshi': {
    image: 'https://www.judopourtous.com/Images/NeHaneGoshi.gif',
    prise: 'classique',
    variante: [],
    contactHanche: 'frontal',
    directionAR: 'avant',
    directionLaterale: 'gauche',
    deplacementUke: 'avance',
  },
  'KubiNage': {
    image: 'https://www.judopourtous.com/Images/NeKubiNage.gif',
    prise: undefined,
    variante: [],
    contactHanche: 'frontal',
    directionAR: 'avant',
    directionLaterale: undefined,
    deplacementUke: 'statique',
  },
  'KoshiUchiMata': {
    image: 'https://www.judopourtous.com/Images/NeKoshiUchiMata.gif',
    prise: 'classique',
    variante: [],
    contactHanche: 'frontal',
    directionAR: 'avant',
    directionLaterale: 'gauche',
    deplacementUke: 'avance',
  },
  'UshiroGoshi': {
    image: 'https://www.judopourtous.com/Images/NeUshiroGoshi.gif',
    prise: 'classique',
    variante: [],
    contactHanche: 'lateral',
    directionAR: 'arriere',
    directionLaterale: undefined,
    deplacementUke: 'recule',
  },
  // Variantes contextuelles
  'OTsuriGoshi': {
    image: 'https://www.judopourtous.com/Images/NeOTsuriGoshi.gif',
    prise: 'classique',
    variante: [],
    contactHanche: 'frontal',
    directionAR: 'avant',
    directionLaterale: undefined,
    deplacementUke: 'avance',
  },
  'KoTsuriGoshi': {
    image: 'https://www.judopourtous.com/Images/NeKoTsuriGoshi.gif',
    prise: 'classique',
    variante: [],
    contactHanche: 'frontal',
    directionAR: 'avant',
    directionLaterale: undefined,
    deplacementUke: 'avance',
  },
  'UchiMataSukashi': {
    image: 'https://www.judopourtous.com/Images/NeUchiMataSukashi.gif',
    prise: undefined,
    variante: [],
    contactHanche: 'frontal',
    directionAR: undefined,
    directionLaterale: undefined,
    deplacementUke: 'lateral',
  },
};

export const sutemiWaza: {[name: string]: SutemiWaza} = {
  'TomoeNage': {
    image: 'https://www.judopourtous.com/Images/NeTomoeNage.gif',
    prise: 'classique',
    variante: [],
    directionChuteTori: 'arriere',
    directionAR: 'arriere',
    directionLaterale: undefined,
    deplacementUke: 'recule',
  },
  'UraNage': {
    image: 'https://www.judopourtous.com/Images/NeUraNage.gif',
    prise: 'classique',
    variante: ['IdakiSutemi'],
    directionChuteTori: 'arriere',
    directionAR: 'arriere',
    directionLaterale: undefined,
    deplacementUke: 'recule',
  },
  'SumiGaeshi': {
    image: 'https://www.judopourtous.com/Images/NeSumiGaeshi.gif',
    prise: 'classique',
    variante: [],
    directionChuteTori: 'arriere',
    directionAR: 'arriere',
    directionLaterale: undefined,
    deplacementUke: 'recule',
  },

  'YokoGuruma': {
    image: 'https://www.judopourtous.com/Images/NeYokoGuruma.gif',
    prise: 'classique',
    variante: [],
    directionChuteTori: 'laterale',
    directionAR: undefined,
    directionLaterale: 'droite',
    deplacementUke: 'lateral',
  },
  'YokoOtoshi': {
    image: 'https://www.judopourtous.com/Images/NeYokoOtoshi.gif',
    prise: 'classique',
    variante: [],
    directionChuteTori: 'laterale',
    directionAR: undefined,
    directionLaterale: 'droite',
    deplacementUke: 'lateral',
  },
  'YokoGake': {
    image: 'https://www.judopourtous.com/Images/NeYokoGake.gif',
    prise: 'classique',
    variante: [],
    directionChuteTori: 'laterale',
    directionAR: undefined,
    directionLaterale: 'droite',
    deplacementUke: 'lateral',
  },
  'YokoWakare': {
    image: 'https://www.judopourtous.com/Images/NeYokoWakare.gif',
    prise: 'classique',
    variante: [],
    directionChuteTori: 'laterale',
    directionAR: undefined,
    directionLaterale: 'gauche',
    deplacementUke: 'lateral',
  },
  'UkiWaza': {
    image: 'https://www.judopourtous.com/Images/NeUkiWaza.gif',
    prise: 'classique',
    variante: [],
    directionChuteTori: 'laterale',
    directionAR: undefined,
    directionLaterale: 'gauche',
    deplacementUke: 'lateral',
  },
  'TaniOtoshi': {
    image: 'https://www.judopourtous.com/Images/NeTaniOtoshi.gif',
    prise: 'classique',
    variante: [],
    directionChuteTori: 'laterale',
    directionAR: undefined,
    directionLaterale: 'gauche',
    deplacementUke: 'avance',
  },
  'YokoTomoeNage': {
    image: 'https://www.judopourtous.com/Images/NeYokoTomoeNage.gif',
    prise: 'classique',
    variante: [],
    directionChuteTori: 'laterale',
    directionAR: undefined,
    directionLaterale: 'droite',
    deplacementUke: 'lateral',
  },
  'WakiOtoshi': {
    image: 'https://www.judopourtous.com/Images/NeWakiOtoshi.gif',
    prise: 'classique',
    variante: ['SukuriNage'],
    directionChuteTori: 'laterale',
    directionAR: undefined,
    directionLaterale: 'droite',
    deplacementUke: 'lateral',
  },

  // Makikomi Sutemi
  'SotoMakikomi': {
    image: 'https://www.judopourtous.com/Images/NeSotoMakikomi.gif',
    prise: 'classique',
    variante: [],
    directionChuteTori: 'laterale',
    directionAR: undefined,
    directionLaterale: 'droite',
    deplacementUke: 'lateral',
  },
  'UchiMataMakikomi': {
    image: 'https://www.judopourtous.com/Images/NeUchiMataMakikomi.gif',
    prise: 'classique',
    variante: [],
    directionChuteTori: 'laterale',
    directionAR: undefined,
    directionLaterale: 'gauche',
    deplacementUke: 'lateral',
  },
  'KoUchiMakikomi': {
    image: 'https://www.judopourtous.com/Images/NeKoUchiMakikomi.gif',
    prise: 'classique',
    variante: [],
    directionChuteTori: 'laterale',
    directionAR: undefined,
    directionLaterale: 'gauche',
    deplacementUke: 'lateral',
  },
  'OUchiMakikomi': {
    image: 'https://www.judopourtous.com/Images/NeOUchiMakikomi.gif',
    prise: 'classique',
    variante: [],
    directionChuteTori: 'laterale',
    directionAR: undefined,
    directionLaterale: 'gauche',
    deplacementUke: 'lateral',
  },
  'HaraiMakikomi': {
    image: 'https://www.judopourtous.com/Images/NeHaraiMakikomi.gif',
    prise: 'classique',
    variante: [],
    directionChuteTori: 'laterale',
    directionAR: undefined,
    directionLaterale: 'gauche',
    deplacementUke: 'lateral',
  },
  'HaneMakikomi': {
    image: 'https://www.judopourtous.com/Images/NeHaneMakikomi.gif',
    prise: 'classique',
    variante: [],
    directionChuteTori: 'laterale',
    directionAR: undefined,
    directionLaterale: 'droite',
    deplacementUke: 'lateral',
  },

  // Anciennes / rares
  'HikkomiGaeshi': {
    image: 'https://www.judopourtous.com/Images/NeHikkomiGaeshi.gif',
    prise: undefined,
    variante: ['ObiToriGaeshi'],
    directionChuteTori: 'arriere',
    directionAR: 'arriere',
    directionLaterale: undefined,
    deplacementUke: 'recule',
  },
  'TawaraGaeshi': {
    image: 'https://www.judopourtous.com/Images/NeTawaraGaeshi.gif',
    prise: undefined,
    variante: [],
    directionChuteTori: 'arriere',
    directionAR: 'arriere',
    directionLaterale: undefined,
    deplacementUke: 'recule',
  },
  'DakiWakare': {
    image: 'https://www.judopourtous.com/Images/NeDakiWakare.gif',
    prise: undefined,
    variante: [],
    directionChuteTori: 'arriere',
    directionAR: 'arriere',
    directionLaterale: undefined,
    deplacementUke: 'recule',
  },
};

export type TechniqueCategory = 'Osaekomi' | 'Shime' | 'Kansetsu' | 'Ashi' | 'Te' | 'Koshi' | 'Sutemi';

export interface TechniqueEntry {
    name: string;
    category: TechniqueCategory;
    data: any;
}

export const TECHNIQUES: TechniqueEntry[] = [];

function pushMap(map: {[name:string]: any}, category: TechniqueCategory) {
    Object.keys(map).forEach(name => {
        TECHNIQUES.push({ name, category, data: map[name] });
    });
}

pushMap(osaekomiWaza, 'Osaekomi');
pushMap(shimeWaza, 'Shime');
pushMap(kansetsuWaza, 'Kansetsu');
pushMap(ashiWaza, 'Ashi');
pushMap(teWaza, 'Te');
pushMap(koshiWaza, 'Koshi');
pushMap(sutemiWaza, 'Sutemi');

export default TECHNIQUES;