import {OsaekomiWaza, ShimeWaza, TeWaza, AshiWaza, KansetsuWaza, KoshiWaza, SutemiWaza} from './types';

export const osaekomiWaza: { [name: string]: OsaekomiWaza } = {
    'KesaGatame': {
        image: 'https://www.judopourtous.com/Images/NeHonGesaGatame.gif',
        prise: undefined,
        positionTori: 'dessus',
        variante: ['KuzureKesaGatame']
    },
    'KuzureKesaGatame': {
        image: 'https://www.judopourtous.com/Images/NeHonGesaGatame.gif',
        prise: undefined,
        positionTori: 'dessus',
    },
    'TateShihoGatame': {
        image: 'https://www.judopourtous.com/Images/NeTateShihoGatame.gif',
        prise: undefined,
        positionTori: 'dessus',
    },
    'UshiroKesaGatame': {
        image: 'https://www.judopourtous.com/Images/NeUshiroGesaGatame.gif',
        prise: undefined,
        positionTori: 'derriere',
    },
    'KamiShihoGatame': {
        image: 'https://www.judopourtous.com/Images/NeKamiShihoGatame.gif',
        prise: undefined,
        positionTori: 'dessus',
    },
    'KuzureKamiShihoGatame': {
        image: 'https://www.judopourtous.com/Images/NeKamiShihoGatame.gif',
        prise: undefined,
        positionTori: 'dessus',
    },
    'YokoShihoGatame': {
        image: 'https://www.judopourtous.com/Images/NeYokoShihoGatame.gif',
        prise: undefined,
        positionTori: 'cote',
        variante: ['KuzureYokoShihoGatame']
    },
    'KuzureYokoShihoGatame': {
        image: 'https://www.judopourtous.com/Images/NeYokoShihoGatame.gif',
        prise: undefined,
        positionTori: 'cote',
    },
    'UkiGatame': {
        image: 'https://www.judopourtous.com/Images/TechniquesOublieesUkiGatame.jpg',
        prise: undefined,
        positionTori: 'dessus',
    },
    'KataGatame': {
        image: 'https://www.judopourtous.com/Images/NeKataGatame.gif',
        prise: undefined,
        positionTori: 'cote',
    },
    'KuzureKataGatame': {
        image: 'https://www.judopourtous.com/Images/NeKataGatame.gif',
        prise: undefined,
        positionTori: 'cote',
    }
};

export const shimeWaza: {[name: string]: ShimeWaza} = {
  'HadakaJime': {
    image: 'https://www.judopourtous.com/Images/NeHadakaJime.gif',
    prise: 'sansGi',
    variante: ['KataHaJime'],
    positionUke: 'dos',
    positionTori: 'dessus',
    type: 'sanguin',
    membresUtilises: ['bras'],
    directionPression: 'circulaire',
  },
  'JujiJime': {
    image: 'https://www.judopourtous.com/Images/NeGyakuJujiJime.gif',
    prise: 'croisee',
    positionUke: 'dos',
    positionTori: 'dessus',
    type: 'sanguin',
    membresUtilises: ['bras','revers'],
    directionPression: 'circulaire',
  },
  'OkuriEriJime': {
    image: 'https://www.judopourtous.com/Images/NeOkuriEriJime.gif',
    prise: 'classique',
    positionUke: 'debout',
    positionTori: 'derriere',
    type: 'sanguin',
    membresUtilises: ['bras','revers'],
    directionPression: 'laterale',
  },
  'KataJujiJime': {
    image: 'https://www.judopourtous.com/Images/NeTsukkomiJime.gif',
    prise: 'croisee',
    positionUke: 'dos',
    positionTori: 'dessus',
    type: 'sanguin',
    membresUtilises: ['bras','revers'],
    directionPression: 'circulaire',
  },
  'NamiJujiJime': {
    image: 'https://www.judopourtous.com/Images/NeTsukkomiJime.gif',
    prise: 'croisee',
    positionUke: 'dos',
    positionTori: 'dessus',
    type: 'sanguin',
    membresUtilises: ['bras','revers'],
    directionPression: 'circulaire',
  },
  'GyakuJujiJime': {
    image: 'https://www.judopourtous.com/Images/NeTsukkomiJime.gif',
    prise: 'croisee',
    positionUke: 'dos',
    positionTori: 'dessus',
    type: 'sanguin',
    membresUtilises: ['bras','revers'],
    directionPression: 'circulaire',
  },
  'KataHaJime': {
    image: 'https://www.judopourtous.com/Images/NeKataHaJime.gif',
    prise: 'croisee',
    positionUke: 'dos',
    positionTori: 'dessus',
    type: 'sanguin',
    membresUtilises: ['bras','revers'],
    directionPression: 'circulaire',
  },
  'SodeGurumaJime': {
    image: 'https://www.judopourtous.com/Images/NeSodeGurumaJime.gif',
    prise: 'doubleRevers',
    positionUke: 'dos',
    positionTori: 'dessus',
    type: 'sanguin',
    membresUtilises: ['bras','revers'],
    directionPression: 'circulaire',
  },
  'KataEriJime': {
    image: 'https://www.judopourtous.com/Images/NeKataTeJime.jpg',
    prise: 'classique',
    positionUke: 'dos',
    positionTori: 'dessus',
    type: 'sanguin',
    membresUtilises: ['bras'],
    directionPression: 'circulaire',
  },
  'OkuriEriJimeAssis': {
    image: 'https://www.judopourtous.com/Images/NeOkuriEriJime.gif',
    prise: 'classique',
    positionUke: 'assis',
    positionTori: 'derriere',
    type: 'sanguin',
    membresUtilises: ['bras','revers'],
    directionPression: 'laterale',
  },
  'TsukkomiJime': {
    image: 'https://www.judopourtous.com/Images/NeTsukkomiJime.gif',
    prise: 'classique',
    positionUke: 'ventre',
    positionTori: 'dessus',
    type: 'respiratoire',
    membresUtilises: ['bras'],
    directionPression: 'laterale',
  },
};

export const kansetsuWaza: {[name: string]: KansetsuWaza} = {
  'JujiGatame': {
    image: 'https://www.jc-langegardien.fr/wp-content/uploads/2011/06/juji_gatame.gif',
    prise: 'classique',
    positionUke: 'dos',
    positionTori: 'dessus',
    articulation: 'coude',
    typeLevier: 'hyperextension',
  },
  'UdeGarami': {
    image: 'https://www.jc-langegardien.fr/wp-content/uploads/2011/06/ude_garami.gif',
    prise: 'classique',
    positionUke: 'dos',
    positionTori: 'dessus',
    articulation: 'coude',
    typeLevier: 'torsion',
  },
  'UdeHishigiUdeGatame': {
    image: 'https://judo-lemanique.ch/wp-content/uploads/2021/04/Ude-Hishigi-Ude-Gatame-removebg-preview.png',
    prise: 'classique',
    positionUke: 'dos',
    positionTori: 'dessus',
    articulation: 'coude',
    typeLevier: 'hyperextension',
  },
  'UdeHishigiJujiGatame': {
    image: 'https://judo-lemanique.ch/wp-content/uploads/2021/04/Ude-Hishigi-Jugi-Gatame-removebg-preview.png',
    prise: 'classique',
    positionUke: 'dos',
    positionTori: 'dessus',
    articulation: 'coude',
    typeLevier: 'hyperextension',
  },
  'UdeHishigiHizaGatame': {
    image: 'https://www.judosport.net/technik/udehishigihiza1.240x150.gif',
    prise: 'classique',
    positionUke: 'cote',
    positionTori: 'cote',
    articulation: 'coude',
    typeLevier: 'hyperextension',
  },
  'UdeHishigiWakiGatame': {
    image: 'https://judo-lemanique.ch/wp-content/uploads/2021/04/Ude-Hishigi-Waki-Gatame-removebg-preview-1.png',
    prise: 'classique',
    positionUke: 'ventre',
    positionTori: 'dessus',
    articulation: 'coude',
    typeLevier: 'hyperextension',
  },
  'UdeHishigiHaraGatame': {
    image: 'https://judo-lemanique.ch/wp-content/uploads/2021/04/ude-hishigi-hara-gatame-removebg-preview.png',
    prise: 'classique',
    positionUke: 'ventre',
    positionTori: 'dessus',
    articulation: 'coude',
    typeLevier: 'hyperextension',
  },
  'UdeHishigiAshiGatame': {
    image: 'https://judo-lemanique.ch/wp-content/uploads/2021/04/ude-shigi-ashi-gatame-removebg-preview.png',
    prise: 'classique',
    positionUke: 'dos',
    positionTori: 'cote',
    articulation: 'coude',
    typeLevier: 'hyperextension',
  },
  'AshiGarami': {
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRUpyQoU23PrWl9IgS-SFNvCjYZXM6Hm0RIaQ&s',
    prise: undefined,
    positionUke: 'cote',
    positionTori: 'cote',
    articulation: 'coude',
    typeLevier: 'torsion',
  },
};

export const ashiWaza: {[name: string]: AshiWaza} = {
  'DeAshiHarai': {
    image: 'https://upload.wikimedia.org/wikipedia/commons/1/1c/De-ashi-barai.jpg',
    prise: 'classique',
    variante: [],
    action: 'balayage',
    directionAR: undefined,
    directionLaterale: undefined,
    deplacementUke: 'lateral',
  },
  'OkuriAshiHarai': {
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Okuri-ashi-barai.jpg/250px-Okuri-ashi-barai.jpg',
    prise: 'classique',
    variante: [],
    action: 'balayage',
    directionAR: undefined,
    directionLaterale: undefined,
    deplacementUke: 'lateral',
  },
  'SasaeTsuriKomiAshi': {
    image: 'https://upload.wikimedia.org/wikipedia/commons/3/3a/Sasae-tsuri-komi-ashi.jpg',
    prise: 'classique',
    variante: [],
    action: 'blocage',
    directionAR: 'avant',
    directionLaterale: undefined,
    deplacementUke: 'statique',
  },
  'HizaGuruma': {
    image: 'https://upload.wikimedia.org/wikipedia/commons/9/9e/Hiza-guruma.jpg',
    prise: 'classique',
    variante: [],
    action: 'blocage',
    directionAR: 'avant',
    directionLaterale: undefined,
    deplacementUke: 'statique',
  },
  'KoSotoGari': {
    image: 'https://upload.wikimedia.org/wikipedia/commons/3/34/Ko-soto-gari.jpg',
    prise: 'classique',
    variante: [],
    action: 'fauchage',
    directionAR: undefined,
    directionLaterale: 'droite',
    deplacementUke: 'statique',
  },
  'KoSotoGake': {
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQqo_cxqj2q2-7F3OP4BbEbgAVII-OoEZuXRQ&s',
    prise: 'classique',
    variante: [],
    action: 'blocage',
    directionAR: undefined,
    directionLaterale: 'droite',
    deplacementUke: 'statique',
  },
  'KoUchiGari': {
    image: 'https://upload.wikimedia.org/wikipedia/commons/e/ee/Ko-uchi-gari.jpg',
    prise: 'classique',
    variante: [],
    action: 'fauchage',
    directionAR: undefined,
    directionLaterale: 'gauche',
    deplacementUke: 'statique',
  },
  'OUchiGari': {
    image: 'https://upload.wikimedia.org/wikipedia/commons/6/61/O-uchi-gari.jpg',
    prise: 'classique',
    variante: [],
    action: 'fauchage',
    directionAR: 'arriere',
    directionLaterale: undefined,
    deplacementUke: 'avance',
  },
  'AshiUchiMata': {
    image: 'https://www.judopourtous.com/Images/TachiUchiMataAshi.jpg',
    prise: 'classique',
    variante: ['KoUchiMata','OUchiMata','TakaUchiMata'],
    action: 'fauchage',
    directionAR: 'avant',
    directionLaterale: undefined,
    deplacementUke: 'avance',
  },
  'OSotoGari': {
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/O-soto-gari.jpg/250px-O-soto-gari.jpg',
    prise: 'classique',
    variante: [],
    action: 'fauchage',
    directionAR: 'arriere',
    directionLaterale: undefined,
    deplacementUke: 'recule',
  },
  'OSotoGuruma': {
    image: 'https://upload.wikimedia.org/wikipedia/commons/b/b2/O-soto-guruma.jpg',
    prise: 'classique',
    variante: [],
    action: 'blocage',
    directionAR: undefined,
    directionLaterale: undefined,
    deplacementUke: 'statique',
  },
  'HaraiTsurikomiAshi': {
    image: 'https://judo-lemanique.ch/wp-content/uploads/2022/01/Harai-tsurikomi-ashi-removebg-preview.png',
    prise: 'classique',
    variante: [],
    action: 'balayage',
    directionAR: 'arriere',
    directionLaterale: undefined,
    deplacementUke: 'avance',
  },
  'AshiGuruma': {
    image: 'https://judo-lemanique.ch/wp-content/uploads/2021/04/Ashi-guruma-removebg-preview.png',
    prise: 'classique',
    variante: [],
    action: 'blocage',
    directionAR: undefined,
    directionLaterale: undefined,
    deplacementUke: 'statique',
  },
  'OGuruma': {
    image: 'https://upload.wikimedia.org/wikipedia/commons/b/b8/O-guruma.jpg',
    prise: 'classique',
    variante: [],
    action: 'blocage',
    directionAR: undefined,
    directionLaterale: undefined,
    deplacementUke: 'statique',
  },
  'TsubameGaeshi': {
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRtzpux8yqNsplaqFtDqwCShX2iWDwaMLqcuw&s',
    prise: undefined,
    action: 'balayage',
    directionAR: undefined,
    directionLaterale: undefined,
    deplacementUke: 'recule',
  },
  'OSotoGaeshi': {
    image: 'https://upload.wikimedia.org/wikipedia/commons/b/bb/O-soto-otoshi.jpg',
    prise: undefined,
    action: 'fauchage',
    directionAR: undefined,
    directionLaterale: undefined,
    deplacementUke: 'recule',
  },
  'OUchiGaeshi': {
    image: 'https://www.judo-ch.jp/english/dictionary/technique/nage/asi/ooutigaesi/image-mfi/img01.gif',
    prise: undefined,
    action: 'fauchage',
    directionAR: undefined,
    directionLaterale: undefined,
    deplacementUke: 'recule',
  },
  'KoUchiGaeshi': {
    image: 'https://www.judo-encyclopedia.com/wp-content/uploads/2022/07/16.-Ko-uchi-gaeshi.jpg',
    prise: undefined,
    action: 'fauchage',
    directionAR: undefined,
    directionLaterale: undefined,
    deplacementUke: 'recule',
  },
  'UchiMataGaeshi': {
    image: 'https://judo-lemanique.ch/wp-content/uploads/2021/04/Uchimata-removebg-preview.png',
    prise: undefined,
    action: 'balayage',
    directionAR: undefined,
    directionLaterale: undefined,
    deplacementUke: 'recule',
  },
};

export const teWaza: {[name: string]: TeWaza} = {
  'IpponSeoiNage': {
    image: 'https://upload.wikimedia.org/wikipedia/commons/c/c1/Ippon-seoi-nage.jpg',
    prise: 'classique',
    variante: ['KatateSeoiNage'],
    brasDominant: 'droite',
    tractionPrincipale: 'avant',
    directionAR: 'avant',
    directionLaterale: undefined,
    deplacementUke: 'avance',
  },
  'MoroteSeoiNage': {
    image: 'https://upload.wikimedia.org/wikipedia/commons/8/8d/Morote-seoi-nage.jpg',
    prise: 'classique',
    variante: [],
    brasDominant: 'droite',
    tractionPrincipale: 'avant',
    directionAR: 'avant',
    directionLaterale: undefined,
    deplacementUke: 'avance',
  },
  'EriSeoiNage': {
    image: 'https://atlantiquejudo.com/wp-content/uploads/2020/01/eriseoinage.gif',
    prise: 'croisee',
    variante: ['KataEriSeoi'],
    brasDominant: 'droite',
    tractionPrincipale: 'circulaire',
    directionAR: 'avant',
    directionLaterale: undefined,
    deplacementUke: 'avance',
  },
  'TaiOtoshi': {
    image: 'https://judo-lemanique.ch/wp-content/uploads/2021/04/Tai-otoshi-removebg-preview.png',
    prise: 'classique',
    variante: [],
    brasDominant: 'droite',
    tractionPrincipale: 'avant',
    directionAR: 'avant',
    directionLaterale: undefined,
    deplacementUke: 'statique',
  },
  'SumiOtoshi': {
    image: 'https://upload.wikimedia.org/wikipedia/commons/2/23/Sumi-otoshi.jpg',
    prise: 'classique',
    variante: [],
    brasDominant: 'droite',
    tractionPrincipale: 'circulaire',
    directionAR: undefined,
    directionLaterale: 'gauche',
    deplacementUke: 'statique',
  },
  'KataGuruma': {
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRZKWPzvBvJA0QkploizWEtpH5vtzKGu2v9gQ&s',
    prise: 'classique',
    variante: [],
    brasDominant: 'droite',
    tractionPrincipale: 'haut',
    directionAR: 'avant',
    directionLaterale: undefined,
    deplacementUke: 'statique',
  },
  'UkiOtoshi': {
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Uki-otoshi.jpg/250px-Uki-otoshi.jpg',
    prise: 'classique',
    variante: [],
    brasDominant: 'droite',
    tractionPrincipale: 'circulaire',
    directionAR: 'avant',
    directionLaterale: undefined,
    deplacementUke: 'statique',
  },
  'TeGuruma': {
    image: 'https://judo-lemanique.ch/wp-content/uploads/2022/01/Te-Guruma-removebg-preview.png',
    prise: 'classique',
    variante: ['SukuiNage'],
    brasDominant: 'droite',
    tractionPrincipale: 'haut',
    directionAR: 'avant',
    directionLaterale: undefined,
    deplacementUke: 'statique',
  },
  'MoroteGari': {
    image: 'https://judo-lemanique.ch/wp-content/uploads/2022/01/Morote-gari.svg-removebg-preview.png',
    prise: undefined,
    variante: [],
    brasDominant: 'droite',
    tractionPrincipale: 'haut',
    directionAR: undefined,
    directionLaterale: undefined,
    deplacementUke: 'avance',
  },
  'KuchikiDaoshi': {
    image: 'https://judo-lemanique.ch/wp-content/uploads/2022/01/Kuchiki-Taoshi-removebg-preview.png',
    prise: undefined,
    variante: [],
    brasDominant: 'droite',
    tractionPrincipale: 'circulaire',
    directionAR: undefined,
    directionLaterale: undefined,
    deplacementUke: 'recule',
  },
  'KibisuGaeshi': {
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSFWQezKm0ohMD6DzXZyxn7KMg_dahj5Ouw7w&s',
    prise: undefined,
    variante: [],
    brasDominant: 'droite',
    tractionPrincipale: 'avant',
    directionAR: undefined,
    directionLaterale: undefined,
    deplacementUke: 'lateral',
  },
};

export const koshiWaza: {[name: string]: KoshiWaza} = {
  'OGoshi': {
    image: 'https://upload.wikimedia.org/wikipedia/commons/7/72/O-goshi.jpg',
    prise: 'classique',
    variante: [],
    contactHanche: 'frontal',
    directionAR: 'avant',
    directionLaterale: undefined,
    deplacementUke: 'avance',
  },
  'KoshiGuruma': {
    image: 'https://upload.wikimedia.org/wikipedia/commons/2/26/Koshi-guruma.jpg',
    prise: 'classique',
    variante: [],
    contactHanche: 'frontal',
    directionAR: 'avant',
    directionLaterale: undefined,
    deplacementUke: 'statique',
  },
  'TsuriGoshi': {
    image: 'https://upload.wikimedia.org/wikipedia/commons/e/e2/Tsuri-goshi.jpg',
    prise: 'classique',
    variante: ['OTsuriGoshi','KoTsuriGoshi'],
    contactHanche: 'frontal',
    directionAR: 'avant',
    directionLaterale: undefined,
    deplacementUke: 'avance',
  },
  'SodeTsuriKomiGoshi': {
    image: 'https://judo-lemanique.ch/wp-content/uploads/2021/04/Sode-tsuri-komi-goshi-removebg-preview.png',
    prise: 'croisee',
    variante: [],
    contactHanche: 'frontal',
    directionAR: 'avant',
    directionLaterale: undefined,
    deplacementUke: 'statique',
  },
  'UkiGoshi': {
    image: 'https://upload.wikimedia.org/wikipedia/commons/c/c7/Uki-goshi2.jpg',
    prise: 'classique',
    variante: [],
    contactHanche: 'frontal',
    directionAR: 'avant',
    directionLaterale: undefined,
    deplacementUke: 'statique',
  },
  'UtsuriGoshi': {
    image: 'https://upload.wikimedia.org/wikipedia/commons/6/6e/Utsuri-goshi.jpg',
    prise: 'classique',
    variante: [],
    contactHanche: 'frontal',
    directionAR: undefined,
    directionLaterale: undefined,
    deplacementUke: 'lateral',
  },
  'HaraiGoshi': {
    image: 'https://upload.wikimedia.org/wikipedia/commons/d/dc/Harai-goshi.jpg',
    prise: 'classique',
    variante: [],
    contactHanche: 'frontal',
    directionAR: 'avant',
    directionLaterale: 'droite',
    deplacementUke: 'avance',
  },
  'HaneGoshi': {
    image: 'https://upload.wikimedia.org/wikipedia/commons/2/2b/Hane-goshi.jpg',
    prise: 'classique',
    variante: [],
    contactHanche: 'frontal',
    directionAR: 'avant',
    directionLaterale: 'gauche',
    deplacementUke: 'avance',
  },
  'KubiNage': {
    image: 'https://judo-lemanique.ch/wp-content/uploads/2021/04/Kubi-Nage.png',
    prise: undefined,
    variante: [],
    contactHanche: 'frontal',
    directionAR: 'avant',
    directionLaterale: undefined,
    deplacementUke: 'statique',
  },
  'KoshiUchiMata': {
    image: 'https://www.judopourtous.com/Images/TachiUchiMataKoshi.jpg',
    prise: 'classique',
    variante: [],
    contactHanche: 'frontal',
    directionAR: 'avant',
    directionLaterale: 'gauche',
    deplacementUke: 'avance',
  },
  'UshiroGoshi': {
    image: 'https://upload.wikimedia.org/wikipedia/commons/c/cd/Ushiro-goshi.jpg',
    prise: 'classique',
    variante: [],
    contactHanche: 'lateral',
    directionAR: 'arriere',
    directionLaterale: undefined,
    deplacementUke: 'recule',
  },
  'OTsuriGoshi': {
    image: 'https://upload.wikimedia.org/wikipedia/commons/e/e2/Tsuri-goshi.jpg',
    prise: 'classique',
    variante: [],
    contactHanche: 'frontal',
    directionAR: 'avant',
    directionLaterale: undefined,
    deplacementUke: 'avance',
  },
  'KoTsuriGoshi': {
    image: 'https://upload.wikimedia.org/wikipedia/commons/e/e2/Tsuri-goshi.jpg',
    prise: 'classique',
    variante: [],
    contactHanche: 'frontal',
    directionAR: 'avant',
    directionLaterale: undefined,
    deplacementUke: 'avance',
  },
  'UchiMataSukashi': {
    image: 'https://www.jc-langegardien.fr/wp-content/uploads/2011/06/Uchi-mata-sukashi2.gif',
    prise: undefined,
    variante: [],
    contactHanche: 'frontal',
    directionAR: undefined,
    directionLaterale: undefined,
    deplacementUke: 'lateral',
  },
};

export const sutemiWaza: {[name: string]: SutemiWaza} = {
  'TomoeNage': {
    image: 'https://judo-lemanique.ch/wp-content/uploads/2021/04/Tomoe-nage-removebg-preview.png',
    prise: 'classique',
    variante: [],
    directionChuteTori: 'arriere',
    directionAR: 'arriere',
    directionLaterale: undefined,
    deplacementUke: 'recule',
  },
  'UraNage': {
    image: 'https://upload.wikimedia.org/wikipedia/commons/4/40/Ura-nage_%28cropped%29.jpg',
    prise: 'classique',
    variante: ['IdakiSutemi'],
    directionChuteTori: 'arriere',
    directionAR: 'arriere',
    directionLaterale: undefined,
    deplacementUke: 'recule',
  },
  'SumiGaeshi': {
    image: 'https://upload.wikimedia.org/wikipedia/commons/d/d4/Sumi-gaeshi2.jpg',
    prise: 'classique',
    variante: [],
    directionChuteTori: 'arriere',
    directionAR: 'arriere',
    directionLaterale: undefined,
    deplacementUke: 'recule',
  },

  'YokoGuruma': {
    image: 'https://upload.wikimedia.org/wikipedia/commons/1/14/Yoko-guruma.jpg',
    prise: 'classique',
    variante: [],
    directionChuteTori: 'laterale',
    directionAR: undefined,
    directionLaterale: 'droite',
    deplacementUke: 'lateral',
  },
  'YokoOtoshi': {
    image: 'https://upload.wikimedia.org/wikipedia/commons/d/da/Yoko-otoshi.jpg',
    prise: 'classique',
    variante: [],
    directionChuteTori: 'laterale',
    directionAR: undefined,
    directionLaterale: 'droite',
    deplacementUke: 'lateral',
  },
  'YokoGake': {
    image: 'https://upload.wikimedia.org/wikipedia/commons/0/0d/Yoko-gake.jpg',
    prise: 'classique',
    variante: [],
    directionChuteTori: 'laterale',
    directionAR: undefined,
    directionLaterale: 'droite',
    deplacementUke: 'lateral',
  },
  'YokoWakare': {
    image: 'https://upload.wikimedia.org/wikipedia/commons/3/3a/Yoko-wakare.jpg',
    prise: 'classique',
    variante: [],
    directionChuteTori: 'laterale',
    directionAR: undefined,
    directionLaterale: 'gauche',
    deplacementUke: 'lateral',
  },
  'UkiWaza': {
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLItjYI-p15jPc4ckS3b2t-npb8xp0mwjn8g&s',
    prise: 'classique',
    variante: [],
    directionChuteTori: 'laterale',
    directionAR: undefined,
    directionLaterale: 'gauche',
    deplacementUke: 'lateral',
  },
  'TaniOtoshi': {
    image: 'https://upload.wikimedia.org/wikipedia/commons/f/fe/Tani-otoshi.jpg',
    prise: 'classique',
    variante: [],
    directionChuteTori: 'laterale',
    directionAR: undefined,
    directionLaterale: 'gauche',
    deplacementUke: 'avance',
  },
  'YokoTomoeNage': {
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTmWU7CdI7nXqV1EeY6CVDUhlkVsDSHTSggvw&s',
    prise: 'classique',
    variante: [],
    directionChuteTori: 'laterale',
    directionAR: undefined,
    directionLaterale: 'droite',
    deplacementUke: 'lateral',
  },
  'WakiOtoshi': {
    image: 'https://www.jc-langegardien.fr/wp-content/uploads/2011/06/wakiotoshi.gif',
    prise: 'classique',
    variante: ['SukuriNage'],
    directionChuteTori: 'laterale',
    directionAR: undefined,
    directionLaterale: 'droite',
    deplacementUke: 'lateral',
  },
  'SotoMakikomi': {
    image: 'https://upload.wikimedia.org/wikipedia/commons/7/72/Soto-makikomi2.jpg',
    prise: 'classique',
    variante: [],
    directionChuteTori: 'laterale',
    directionAR: undefined,
    directionLaterale: 'droite',
    deplacementUke: 'lateral',
  },
  'UchiMataMakikomi': {
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQSxnTgOksbchSJEbLWdqyrFOR1_TfwNmXTiA&s',
    prise: 'classique',
    variante: [],
    directionChuteTori: 'laterale',
    directionAR: undefined,
    directionLaterale: 'gauche',
    deplacementUke: 'lateral',
  },
  'KoUchiMakikomi': {
    image: 'https://www.jc-langegardien.fr/wp-content/uploads/2011/06/KoUchiMakikomi.gif',
    prise: 'classique',
    variante: [],
    directionChuteTori: 'laterale',
    directionAR: undefined,
    directionLaterale: 'gauche',
    deplacementUke: 'lateral',
  },
  'OUchiMakikomi': {
    image: 'https://bojovky.info/wp-content/uploads/ouchimakikomi.gif',
    prise: 'classique',
    variante: [],
    directionChuteTori: 'laterale',
    directionAR: undefined,
    directionLaterale: 'gauche',
    deplacementUke: 'lateral',
  },
  'HaraiMakikomi': {
    image: 'https://gimnasiosamurai.es/apkjudo/images/librodejudo/YOKOSUTEMIWAZA/MAKIKOMI/HARAIMAKIKOMI.jpg',
    prise: 'classique',
    variante: [],
    directionChuteTori: 'laterale',
    directionAR: undefined,
    directionLaterale: 'gauche',
    deplacementUke: 'lateral',
  },
  'HaneMakikomi': {
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Hane-makikomi.jpg/250px-Hane-makikomi.jpg',
    prise: 'classique',
    variante: [],
    directionChuteTori: 'laterale',
    directionAR: undefined,
    directionLaterale: 'droite',
    deplacementUke: 'lateral',
  },

  'HikkomiGaeshi': {
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQqAVXllLzfh9ErE0UZtbuMcbrzbBii4WM9eA&s',
    prise: undefined,
    variante: ['ObiToriGaeshi'],
    directionChuteTori: 'arriere',
    directionAR: 'arriere',
    directionLaterale: undefined,
    deplacementUke: 'recule',
  },
  'TawaraGaeshi': {
    image: 'https://www.judo-encyclopedia.com/wp-content/uploads/2022/07/4.-Taware-geashi.jpg',
    prise: undefined,
    variante: [],
    directionChuteTori: 'arriere',
    directionAR: 'arriere',
    directionLaterale: undefined,
    deplacementUke: 'recule',
  },
  'DakiWakare': {
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcThCyYAHliFp7P5UfI6i0UUMrEL-CyBb53bKg&s',
    prise: undefined,
    variante: [],
    directionChuteTori: 'arriere',
    directionAR: 'arriere',
    directionLaterale: undefined,
    deplacementUke: 'recule',
  },
};

export type TechniqueCategory = 'Osaekomi' | 'Shime' | 'Kansetsu' | 'Ashi' | 'Te' | 'Koshi' | 'Sutemi';

export interface TechniqueEntry {
    name: string;
    category: TechniqueCategory;
    data: any;
}

export const TECHNIQUES: TechniqueEntry[] = [];

function pushMap(map: {[name:string]: any}, category: TechniqueCategory) {
    Object.keys(map).forEach(name => {
        TECHNIQUES.push({ name, category, data: map[name] });
    });
}

pushMap(osaekomiWaza, 'Osaekomi');
pushMap(shimeWaza, 'Shime');
pushMap(kansetsuWaza, 'Kansetsu');
pushMap(ashiWaza, 'Ashi');
pushMap(teWaza, 'Te');
pushMap(koshiWaza, 'Koshi');
pushMap(sutemiWaza, 'Sutemi');

export default TECHNIQUES;